keys:
  - &hex 4485686BB93BF3ED22E34070AB5F80A3F8A2DE61

  - &salt age10uw374gt4pc4v27ftrnw9k9mvxd75hnr8rrdecqhzut9497pz96qfrudxn
  - &palladium age1yknh353ll8yy2l8v6ptm62u0chak2gzrxs4va0qmz343eznu4alsz5rak5
  - &shinonome age1vuxeyq8339n00dgmputde5qa8r7l36vc90demhnnsdmgfj4yfp3qj68ykr

creation_rules:
  - path_regex: nixos/shinonome/secrets\.yaml$
    key_groups:
      - pgp:
          - *hex
        age:
          - *shinonome
  - path_regex: nixos/salt/secrets\.yaml$
    key_groups:
      - pgp:
          - *hex
        age:
          - *salt
  - path_regex: nixos/palladium/secrets\.yaml$
    key_groups:
      - pgp:
          - *hex
        age:
          - *palladium
  - key_groups:
      - pgp:
          - *hex
        age:
          - *salt
          - *palladium
          - *shinonome
