# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "mpt3sas" ];
  boot.initrd.kernelModules = [ ];
  boot.initrd.supportedFilesystems = [ "zfs" ];
  boot.kernelModules = [ "kvm-amd" "mlx4_core" "mlx4_en" "mlx4_ib" "vfio-pci" ];
  boot.extraModulePackages = [ ];

  # boot.kernelParams = [ "zfs.zfs_dmu_offset_next_sync=0" ];
  #boot.kernelParams = [ "resume=UUID=e117d62d-6440-4b27-bbb5-1db1458d1e00" ];

  fileSystems."/" =
    {
      device = "salt/ROOT";
      fsType = "zfs";
      options = [ "zfsutil" "X-mount.mkdir" ];
      neededForBoot = true;
    };

  fileSystems."/home" =
    {
      device = "salt/HOME";
      fsType = "zfs";
      options = [ "zfsutil" "X-mount.mkdir" ];
      neededForBoot = true;
    };

  fileSystems."/nix" =
    {
      device = "salt/NIX";
      fsType = "zfs";
      options = [ "zfsutil" "X-mount.mkdir" ];
      neededForBoot = true;
    };

  fileSystems."/Plain/home" =
    {
      device = "Plain/home";
      fsType = "zfs";
      options = [ "zfsutil" "X-mount.mkdir" ];
      neededForBoot = true;
    };

  fileSystems."/Plain/Games" =
    {
      device = "Plain/Games";
      fsType = "zfs";
      options = [ "zfsutil" "X-mount.mkdir" ];
      neededForBoot = true;
    };

  fileSystems."/Plain/Videos" =
    {
      device = "Plain/Videos";
      fsType = "zfs";
      options = [ "zfsutil" "X-mount.mkdir" ];
      neededForBoot = true;
    };

  fileSystems."/Plain/Downloads" =
    {
      device = "Plain/Downloads";
      fsType = "zfs";
      options = [ "zfsutil" "X-mount.mkdir" ];
      neededForBoot = true;
    };

  # fileSystems."/var/lib/docker" =
  #   {
  #     device = "Plain/docker";
  #     fsType = "zfs";
  #     options = [ "zfsutil" "X-mount.mkdir" ];
  #     neededForBoot = true;
  #   };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/DD6D-CCA8";
      fsType = "vfat";
    };

  boot.zfs.requestEncryptionCredentials = [ "salt/HOME" "Plain" ];

  swapDevices = [{
    device = "/dev/disk/by-partuuid/435106f8-d93b-4219-beaa-00087c655c29";
    randomEncryption = {
      enable = true;
    };
  }];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  # hardware.video.hidpi.enable = lib.mkDefault true;
}
