# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "mpt3sas" ];
  boot.initrd.kernelModules = [ ];
  boot.initrd.supportedFilesystems = [ "zfs" ];
  boot.kernelModules = [ "kvm-amd" "mlx4_core" "mlx4_en" "mlx4_ib" "vfio-pci" ];
  boot.extraModulePackages = [ ];

  # boot.kernelParams = [ "zfs.zfs_dmu_offset_next_sync=0" ];
  #boot.kernelParams = [ "resume=UUID=e117d62d-6440-4b27-bbb5-1db1458d1e00" ];

  fileSystems =
    let
      zfs = (dev: {
        device = dev;
        fsType = "zfs";
        options = [ "zfsutil" "X-mount.mkdir" ];
        neededForBoot = true;
      });
    in
    {
      "/boot" = {
        device = "/dev/disk/by-uuid/DD6D-CCA8";
        fsType = "vfat";
      };
      "/" = zfs "Plain/salt/ROOT";
      "/nix" = zfs "Plain/salt/NIX";
      "/home" = zfs "Plain/home";
      "/Plain/Games" = zfs "Plain/Games";
      "/Plain/Downloads" = zfs "Plain/Downloads";
      "/Plain/Videos" = zfs "Plain/Videos";
    };

  # fileSystems."/" =
  #   {
  #     device = "Plain/salt/ROOT";
  #     fsType = "zfs";
  #     options = [ "zfsutil" "X-mount.mkdir" ];
  #     neededForBoot = true;
  #   };

  # fileSystems."/home" =
  #   {
  #     device = "Plain/home";
  #     fsType = "zfs";
  #     options = [ "zfsutil" "X-mount.mkdir" ];
  #     neededForBoot = true;
  #   };

  # fileSystems."/nix" =
  #   {
  #     device = "Plain/salt/NIX";
  #     fsType = "zfs";
  #     options = [ "zfsutil" "X-mount.mkdir" ];
  #     neededForBoot = true;
  #   };

  # fileSystems."/Plain/home" =
  #   {
  #     device = "Plain/home";
  #     fsType = "zfs";
  #     options = [ "zfsutil" "X-mount.mkdir" ];
  #     neededForBoot = true;
  #   };

  # fileSystems."/Plain/Games" =
  #   {
  #     device = "Plain/Games";
  #     fsType = "zfs";
  #     options = [ "zfsutil" "X-mount.mkdir" ];
  #     neededForBoot = true;
  #   };

  # fileSystems."/Plain/Videos" =
  #   {
  #     device = "Plain/Videos";
  #     fsType = "zfs";
  #     options = [ "zfsutil" "X-mount.mkdir" ];
  #     neededForBoot = true;
  #   };

  # fileSystems."/Plain/Downloads" =
  #   {
  #     device = "Plain/Downloads";
  #     fsType = "zfs";
  #     options = [ "zfsutil" "X-mount.mkdir" ];
  #     neededForBoot = true;
  #   };

  # fileSystems."/var/lib/docker" =
  #   {
  #     device = "Plain/docker";
  #     fsType = "zfs";
  #     options = [ "zfsutil" "X-mount.mkdir" ];
  #     neededForBoot = true;
  #   };

  boot.zfs.requestEncryptionCredentials = [ "Plain" ];

  swapDevices = [{
    device = "/dev/disk/by-partuuid/056de308-3750-43e4-86cf-f0950f078aab";
    randomEncryption = {
      enable = true;
    };
  }];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  # hardware.video.hidpi.enable = lib.mkDefault true;
}
